# Site settings
title: Markus Kilås pseudorandom posts
email: markus@markuspage.com
description: > # this means to ignore newlines until "baseurl:"
  Markus blog about random stuff related to crypto, PKI, security, insecurity,
  free and open source software, VoIP/XMPP/SIP, federated social networks, 
  cycling and anything else.
#baseurl: "/markus" # the subpath of your site, e.g. /blog/
url: "https://netmackan.github.io" # the base hostname & protocol for your site
twitter_username: netmackan
#github_username:  netmackan
quitter_username: netmackan

# Build settings
markdown: kramdown
